name: E2E Regression
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '00 21 * * *'
  workflow_dispatch:

jobs:
  chrome_windows_Test:
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - name: checkout Code
        uses: actions/checkout@v5

      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.11

      - name: Running Tests
        run: mvn clean test

      - name: Install Allure CLI
        run: |
          Invoke-WebRequest -Uri https://github.com/allure-framework/allure2/releases/download/2.36.0/allure-2.36.0.zip -OutFile allure.zip
          Expand-Archive allure.zip -DestinationPath $env:USERPROFILE\allure
          $env:PATH = "$env:USERPROFILE\allure\allure-2.36.0\bin;$env:PATH"
          allure --version

      - name: Generate Allure Report
        run: |
          allure generate ./allure-results -o allure-report --clean

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report